-- 코드를 작성해주세요
WITH RECURSIVE ECOLI_GENERATION AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, G.GENERATION + 1
    FROM ECOLI_DATA E
    JOIN ECOLI_GENERATION G ON E.PARENT_ID = G.ID
)

SELECT COUNT(G.ID) AS COUNT, G.GENERATION
FROM ECOLI_GENERATION G
LEFT JOIN ECOLI_DATA D ON G.ID = D.PARENT_ID
WHERE D.ID IS NULL
GROUP BY G.GENERATION
ORDER BY G.GENERATION ASC;