-- 코드를 입력하세요
WITH RENTAL_DATA AS (
    SELECT R.HISTORY_ID, C.CAR_TYPE, C.DAILY_FEE, DATEDIFF(R.END_DATE, R.START_DATE) + 1 AS DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY R
    JOIN CAR_RENTAL_COMPANY_CAR C ON R.CAR_ID = C.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
)

SELECT R.HISTORY_ID, ROUND(R.DAILY_FEE * R.DURATION * (100 - IFNULL(D.DISCOUNT_RATE, 0)) / 100) AS FEE
FROM RENTAL_DATA R
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D ON R.CAR_TYPE = D.CAR_TYPE
    AND D.DURATION_TYPE = (
        CASE WHEN R.DURATION >= 90 THEN '90일 이상'
        WHEN R.DURATION >= 30 THEN '30일 이상'
        WHEN R.DURATION >= 7 THEN '7일 이상'
        ELSE NULL END
    )
ORDER BY FEE DESC, R.HISTORY_ID DESC;