-- 코드를 입력하세요
WITH RECURSIVE TIME_TABLE AS (
    SELECT 0 AS HOUR -- 시작 숫자 0
    UNION ALL
    SELECT HOUR + 1 FROM TIME_TABLE WHERE HOUR < 23 -- 23이 될 때까지 1씩 더함
)

SELECT T.HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM TIME_TABLE T
LEFT JOIN ANIMAL_OUTS A ON T.HOUR = HOUR(A.DATETIME)
GROUP BY T.HOUR
ORDER BY T.HOUR;